import { useState } from 'react';
import { ChevronDown, RotateCcw, SlidersHorizontal, Sparkles } from 'lucide-react';
import type { Criteria, CriteriaPatch, UtilityName } from '../domain/schema.js';
import { capWhole, dollars, utilities } from '../lib/view.js';

type Props = { criteria: Criteria; baseline: Criteria; onPatch: (patch: CriteriaPatch) => void; onRevert: () => void; onDestinationEdit: () => void };

export function CriteriaBar({ criteria, baseline, onPatch, onRevert, onDestinationEdit }: Props) {
  const [open, setOpen] = useState<string | null>(null);
  const [rent, setRent] = useState(String(criteria.personalRentCap / 100));
  const [occupants, setOccupants] = useState(criteria.allocation.occupants);
  const [walk, setWalk] = useState(String(criteria.maxWalkSeconds / 60));
  const [beds, setBeds] = useState(criteria.bedrooms);
  const [baths, setBaths] = useState(criteria.minBathrooms);
  const [niche, setNiche] = useState(criteria.nicheQuery ?? '');
  const [mobileOpen, setMobileOpen] = useState(false);
  const isChanged = JSON.stringify({ ...criteria, nicheQuery: null }) !== JSON.stringify({ ...baseline, nicheQuery: null });
  const toggle = (key: string) => setOpen(value => value === key ? null : key);
  const close = () => setOpen(null);
  return <div className={`criteria-wrap ${mobileOpen ? 'mobile-open' : ''}`}>
    <button className="mobile-criteria-summary" onClick={() => setMobileOpen(value => !value)} aria-expanded={mobileOpen} aria-label="Edit current search requirements"><span><strong>{dollars(criteria.personalRentCap)} share</strong> · {criteria.bedrooms}bd · {criteria.minBathrooms}+ba · ≤{Math.round(criteria.maxWalkSeconds/60)} min to {criteria.destination.label.split(' — ')[0]}</span><SlidersHorizontal size={17}/></button>
    <h1 className="criteria-line" aria-label="Current search requirements">
      <span className="criteria-intro">Your search</span>
      <div className="criterion"><button className="criterion-trigger" type="button" onClick={() => { setRent(String(criteria.personalRentCap / 100)); toggle('rent'); }} aria-expanded={open === 'rent'}>Your share <strong>{dollars(criteria.personalRentCap)}</strong><ChevronDown size={13}/></button>{open === 'rent' && <div className="criterion-pop"><label htmlFor="personal-cap">Maximum monthly rent for your share</label><div className="field-prefix"><span>$</span><input id="personal-cap" type="number" min="0" step="1" value={rent} onChange={e => setRent(e.target.value)} onKeyDown={e => { if (e.key === 'Escape') close(); }} /></div><p>Rent only. Additional charges appear separately.</p><button className="plain-button primary-button" onClick={() => { const value = Number(rent); if (Number.isFinite(value) && value >= 0) onPatch({ personalRentCap: Math.round(value * 100) }); close(); }}>Apply</button></div>}</div>
      <span className="criteria-divider">·</span>
      <div className="criterion"><button className="criterion-trigger" type="button" onClick={() => { setOccupants(criteria.allocation.occupants); toggle('split'); }} aria-expanded={open === 'split'}><strong>{criteria.allocation.kind === 'equal' ? `${criteria.allocation.occupants} equal shares` : `${criteria.allocation.occupants} occupants · custom share`}</strong><span className="assumed-tag">assumed</span><ChevronDown size={13}/></button>{open === 'split' && <div className="criterion-pop"><label htmlFor="occupants">People splitting the whole-home rent, including you</label><input id="occupants" type="number" min="1" max="12" value={occupants} onChange={e => setOccupants(Number(e.target.value))} onKeyDown={e => { if (e.key === 'Escape') close(); }} /><p>Equal shares are a demo assumption. Change it to recompute every personal share.</p><button className="plain-button primary-button" onClick={() => { onPatch({ allocation: { occupants: Math.max(1, Math.min(12, occupants)), kind: 'equal', personalShareBps: null } }); close(); }}>Apply</button></div>}</div>
      <span className="criteria-divider">·</span><span className="home-cap">{dollars(capWhole(criteria))} whole-home ceiling</span>
      <span className="criteria-divider">·</span>
      <div className="criterion"><button className="criterion-trigger" type="button" onClick={() => { setBeds(criteria.bedrooms); setBaths(criteria.minBathrooms); toggle('layout'); }} aria-expanded={open === 'layout'}><strong>{criteria.bedrooms} beds · {criteria.minBathrooms}+ baths</strong><ChevronDown size={13}/></button>{open === 'layout' && <div className="criterion-pop"><div className="two-fields"><label>Bedrooms<input type="number" min="0" max="10" value={beds} onChange={e => setBeds(Number(e.target.value))}/></label><label>Minimum advertised baths<input type="number" min="0" max="10" step="0.5" value={baths} onChange={e => setBaths(Number(e.target.value))}/></label></div><button className="plain-button primary-button" onClick={() => { onPatch({ bedrooms: beds, minBathrooms: baths }); close(); }}>Apply</button></div>}</div>
      <span className="criteria-divider">·</span>
      <div className="criterion"><button className="criterion-trigger" type="button" onClick={() => { setWalk(String(criteria.maxWalkSeconds / 60)); toggle('walk'); }} aria-expanded={open === 'walk'}><strong>{Math.round(criteria.maxWalkSeconds / 60)} min walk</strong><ChevronDown size={13}/></button>{open === 'walk' && <div className="criterion-pop"><label htmlFor="max-walk">Maximum computed walking time in minutes</label><input id="max-walk" type="number" min="1" max="120" value={walk} onChange={e => setWalk(e.target.value)} onKeyDown={e => { if (e.key === 'Escape') close(); }} /><p>Only valid foot routes to the mapped entrance can qualify.</p><button className="plain-button primary-button" onClick={() => { const value = Number(walk); if (Number.isFinite(value) && value > 0) onPatch({ maxWalkSeconds: Math.round(value * 60) }); close(); }}>Apply</button></div>}</div>
      <span>to</span> <button className="destination-link" onClick={onDestinationEdit}>{criteria.destination.label}</button>
      <span className="criteria-divider">·</span>
      <div className="criterion"><button className={`criterion-trigger niche-trigger ${criteria.nicheQuery ? 'has-niche' : ''}`} type="button" onClick={() => { setNiche(criteria.nicheQuery ?? ''); toggle('niche'); }} aria-expanded={open === 'niche'}><Sparkles size={13}/><span>Ask Grok</span>{criteria.nicheQuery && <span className="niche-active-dot" aria-label="Request active"/>}<ChevronDown size={13}/></button>{open === 'niche' && <div className="criterion-pop niche-pop"><label htmlFor="niche-query">Find a feature or nearby place</label><input id="niche-query" autoFocus placeholder="e.g. close to a Chinese supermarket" maxLength={200} value={niche} onChange={e => setNiche(e.target.value)} onKeyDown={e => { if (e.key === 'Escape') close(); if (e.key === 'Enter' && niche.trim()) { onPatch({ nicheQuery: niche.trim() }); close(); } }} /><div className="niche-examples">{['Near a grocery store', 'In-unit laundry', 'Hot tub'].map(example => <button type="button" key={example} onClick={() => setNiche(example)}>{example}</button>)}</div><p>Grok checks the saved research for your request. Suggestions show any compromise on rent, layout, or walking time; your filters stay as you set them.</p><div className="niche-pop-actions">{criteria.nicheQuery && <button className="plain-button" onClick={() => { onPatch({ nicheQuery: null }); setNiche(''); close(); }}>Clear request</button>}<button className="plain-button primary-button" disabled={!niche.trim()} onClick={() => { onPatch({ nicheQuery: niche.trim() }); close(); }}>Find suggestions</button></div></div>}</div>
      <div className="criteria-tail"><button className="more-trigger" onClick={() => toggle('more')} aria-expanded={open === 'more'}><SlidersHorizontal size={15}/> More preferences</button>{isChanged && <button className="revert-trigger" onClick={onRevert}><RotateCcw size={14}/> Revert to original</button>}</div>
    </h1>
    {isChanged && <div className="baseline-note">Original search: {dollars(baseline.personalRentCap)} share · {baseline.allocation.occupants} equal shares · {baseline.bedrooms} beds / {baseline.minBathrooms}+ baths · {baseline.maxWalkSeconds / 60} min walk <span>→ current search above</span></div>}
    {open === 'more' && <div className="more-panel"><div><h3>Property type</h3>{(['house','apartment','room','other'] as const).map(t => <label className="check-label" key={t}><input type="checkbox" checked={criteria.propertyTypes.includes(t)} onChange={e => onPatch({ propertyTypes: e.target.checked ? [...criteria.propertyTypes,t] : criteria.propertyTypes.filter(x => x !== t) })}/>{t[0].toUpperCase()+t.slice(1)}</label>)}</div><div><h3>Require utilities included</h3><p>Only explicitly included utilities count as confirmed.</p>{utilities.map(u => <label className="check-label" key={u.key}><input type="checkbox" checked={criteria.requiredIncludedUtilities.includes(u.key)} onChange={e => onPatch({ requiredIncludedUtilities: e.target.checked ? [...criteria.requiredIncludedUtilities,u.key] : criteria.requiredIncludedUtilities.filter((x: UtilityName) => x !== u.key) })}/>{u.label}</label>)}</div><div><h3>Features</h3>{[['laundry_in_unit','In-unit laundry'],['laundry_on_site','On-site laundry'],['parking','Parking'],['pets_allowed','Pets allowed'],['step_free_access','Step-free access'],['air_conditioning','Air conditioning'],['outdoor_space','Outdoor space']].map(([key,label]) => <label className="check-label" key={key}><input type="checkbox" checked={criteria.mustHaveAmenities.includes(key)} onChange={e => onPatch({ mustHaveAmenities: e.target.checked ? [...criteria.mustHaveAmenities,key] : criteria.mustHaveAmenities.filter(x => x !== key) })}/>{label}</label>)}</div></div>}
  </div>;
}
