import { ArrowUpRight, GitCompareArrows, X } from 'lucide-react';
import type { EvaluatedHome, Home } from '../domain/schema.js';
import { dollars, fitLabel, title } from '../lib/view.js';

type SavedItem = { id: string; home?: Home; result?: EvaluatedHome; meta?: { title: string; url: string } };
type Props = { items: SavedItem[]; compareCount: number; onCompare: () => void; onRemove: (id: string) => void; onSelect: (id: string) => void };
export function ShortlistRail({ items, compareCount, onCompare, onRemove, onSelect }: Props) {
  if (!items.length && compareCount === 0) return null;
  if (!items.length) return <aside className="compare-only-rail" aria-label="Comparison selection"><strong>{compareCount} {compareCount === 1 ? 'option' : 'options'} selected for comparison</strong><span>{compareCount < 2 ? 'Choose one more to compare side by side.' : 'See costs, routes, utilities, and unanswered questions in the same order.'}</span><button className="plain-button" disabled={compareCount < 2} onClick={onCompare}><GitCompareArrows size={15}/> Compare options</button></aside>;
  return <aside className="shortlist-rail" aria-label="Saved shortlist"><div className="shortlist-label"><span className="eyebrow">Ready to investigate</span><strong>{items.length} saved {items.length === 1 ? 'option' : 'options'}</strong><button className="plain-button" disabled={compareCount < 2} onClick={onCompare}><GitCompareArrows size={15}/> Compare {compareCount || 0} selected</button></div><div className="shortlist-items">{items.map(({ id, home, result, meta }) => { const name = home ? title(home) : meta?.title || 'Saved option'; const url = home?.primaryUrl || meta?.url; return <div className="shortlist-item" key={id}><button onClick={() => home && onSelect(id)} disabled={!home}><strong>{name}</strong><span>{!home ? 'Not in the current research snapshot' : result ? `${dollars(result.cost.personalBaseRent)} share · ${fitLabel(result)}` : 'Outside this search'}</span><small>{!home ? 'Check the original source before relying on this option' : result?.questions[0]?.text || 'Check current availability and costs'}</small></button>{url && <a href={url} target="_blank" rel="noreferrer" aria-label={`Open listing for ${name}`}><ArrowUpRight size={14}/></a>}<button className="icon-button" onClick={() => onRemove(id)} aria-label={`Remove ${name} from shortlist`}><X size={15}/></button></div>; })}</div></aside>;
}
