export type RegisteredSource = { id: string; family: string; name: string; url: string; accessMode: 'public_page' | 'index_leads' | 'link_only' | 'unavailable'; limitation: string | null; adapter?: 'cmu' | 'lobos' | 'reinhold' | 'manager' };

export const SOURCE_REGISTRY: RegisteredSource[] = [
  { id: 'cmu-offcampus', family: 'cmu-offcampus', name: 'CMU Off-Campus Housing', url: 'https://offcampus.housing.cmu.edu/listing', accessMode: 'public_page', limitation: 'Public listingData exposes many floorplans; only nearby active 2-bedroom plans are selected, and missing fields remain unknown.', adapter: 'cmu' },
  { id: 'lobos-management', family: 'lobos-management', name: 'Lobos Management', url: 'https://lobosmanagement.com/units', accessMode: 'public_page', limitation: 'Inventory cards expose advertised From prices; exact upper/base unit rent is not inferred.', adapter: 'lobos' },
  { id: 'reinhold-residential', family: 'reinhold-residential', name: 'Reinhold Residential', url: 'https://reinholdresidential.com/properties/shadyside-commons/', accessMode: 'public_page', limitation: 'Public availability table is unit-scoped; utilities are not stated.', adapter: 'reinhold' },
  { id: 'kerpec-management', family: 'kerpec-management', name: 'Kerpec Management', url: 'https://www.kerpecmgt.com/rentals', accessMode: 'link_only', limitation: 'Survey lead; no direct adapter claimed and no retrieval is represented.' },
  { id: 'walnut-capital', family: 'walnut-capital', name: 'Walnut Capital', url: 'https://www.walnutcapital.com/properties/walnut-crossings', accessMode: 'link_only', limitation: 'Survey lead; no direct adapter claimed.' },
  { id: 'zillow', family: 'zillow-group', name: 'Zillow', url: 'https://www.zillow.com/pittsburgh-pa/apartments-2-bedrooms/', accessMode: 'link_only', limitation: 'Terms restrict automated collection/display.' },
  { id: 'trulia', family: 'zillow-group', name: 'Trulia', url: 'https://www.trulia.com/for_rent/Pittsburgh,PA/2p_beds/', accessMode: 'link_only', limitation: 'Zillow Group restrictions; no adapter.' },
  { id: 'hotpads', family: 'zillow-group', name: 'HotPads', url: 'https://hotpads.com/pittsburgh-pa/2-bedroom-apartments-for-rent', accessMode: 'link_only', limitation: 'Zillow Group restrictions; no adapter.' },
  { id: 'apartments-com', family: 'apartments-com-network', name: 'Apartments.com', url: 'https://www.apartments.com/pittsburgh-pa/2-bedrooms/', accessMode: 'link_only', limitation: 'Terms restrict automated copying without authorization.' },
  { id: 'apartmentfinder', family: 'apartments-com-network', name: 'Apartment Finder', url: 'https://www.apartmentfinder.com/Pennsylvania/Pittsburgh-Apartments/2-Bedrooms', accessMode: 'link_only', limitation: 'Same network family as Apartments.com; no source-approved feed.' },
  { id: 'realtor', family: 'realtor', name: 'Realtor.com', url: 'https://www.realtor.com/apartments/Pittsburgh_PA/beds-2-2', accessMode: 'link_only', limitation: 'Survey lead; no source-approved feed.' },
  { id: 'zumper', family: 'zumper', name: 'Zumper', url: 'https://www.zumper.com/apartments-for-rent/pittsburgh-pa/2-beds', accessMode: 'link_only', limitation: 'Survey lead; no source-approved feed.' },
  { id: 'redfin-rentals', family: 'redfin-rentals', name: 'Redfin Rentals', url: 'https://www.redfin.com/city/15702/PA/Pittsburgh/apartments-for-rent/filter/min-beds=2', accessMode: 'link_only', limitation: 'Survey lead; no source-approved feed.' },
  { id: 'rent-com', family: 'rent-com-network', name: 'Rent.com', url: 'https://www.rent.com/pennsylvania/pittsburgh-apartments/2-bedroom', accessMode: 'link_only', limitation: 'Survey lead; no source-approved feed.' },
  { id: 'apartmentguide', family: 'rent-com-network', name: 'ApartmentGuide', url: 'https://www.apartmentguide.com/apartments/Pennsylvania/Pittsburgh/2-beds-1z141y8/', accessMode: 'link_only', limitation: 'Surveyed through sparse public/index results; no verified unit import.' },
  { id: 'padmapper', family: 'zumper', name: 'PadMapper', url: 'https://www.padmapper.com/apartments/pittsburgh-pa/2-beds', accessMode: 'link_only', limitation: 'Surveyed through search indexing; direct page unavailable and no verified unit import.' },
  { id: 'apartment-list', family: 'apartment-list', name: 'Apartment List', url: 'https://www.apartmentlist.com/pa/pittsburgh', accessMode: 'link_only', limitation: 'Public survey only; property averages and availability prompts are not verified unit evidence.' },
  { id: 'homes-com', family: 'homes-com', name: 'Homes.com', url: 'https://www.homes.com/pittsburgh-pa/apartments-for-rent/2-bedroom/', accessMode: 'link_only', limitation: 'Public survey only; no direct adapter or source-approved feed.' },
  { id: 'craigslist-pittsburgh', family: 'craigslist', name: 'Craigslist Pittsburgh', url: 'https://pittsburgh.craigslist.org/apa/', accessMode: 'unavailable', limitation: 'Stale/index snippets and anti-automation; excluded from seed.' },
  { id: 'facebook-marketplace', family: 'meta-marketplace', name: 'Facebook Marketplace', url: 'https://www.facebook.com/marketplace/pittsburgh/propertyrentals/', accessMode: 'unavailable', limitation: 'Authentication/block wall; no bypass.' },
];

export function sourceById(id: string): RegisteredSource { const source = SOURCE_REGISTRY.find((item) => item.id === id); if (!source) throw new Error(`Unknown source ${id}`); return source; }
